Implemented ocutil-mirrorfrom and fixed a bug.
* ocutil-mirrorfrom now fully works, and can create read-only mirrors on
  your OpenChariot server of existing remote repos.

	* This relates to a68/fbd.

* Fixed a bug in ocutil-update-gitstats where it would not correctly
  detect non-empty repos.

* ocutil-update-gitstats now uses the new logging functions.

* oc_log_info and oc_log_debug can now be suppressed by openchariot.cfg
  switches.

diff --git a/src/core/bin/ocutil-spooler b/src/core/bin/ocutil-spooler
--- a/src/core/bin/ocutil-spooler
+++ b/src/core/bin/ocutil-spooler
@@ -25,6 +25,13 @@ if [ $? -ne 0 ] ; then
 	echo "PANIC: ocutil-process-gitspool failed; consult $OC_LOGFILE"
 	exit 1
 fi
+
+ocutil-mirrorfrom >> $OC_LOGFILE 2>&1
+if [ $? -ne 0 ] ; then
+	echo "PANIC: ocutil-mirrorfrom failed; consult $OC_LOGFILE"
+	exit 1
+fi
+
 ocutil-update-be >> $OC_LOGFILE 2>&1
 if [ $? -ne 0 ] ; then
 	echo "PANIC: ocutil-update-be failed; consult $OC_LOGFILE"
