Implement dumb git http protocol
OpenChariot now documents and supports the git "dumb" http protocol for
anonymous clones. This is useful, because users behind firewalls which
block git:// (common for large corperations) will be able to perform
clones.

This feature is, for now, turned on by default, and can be disabled in
ocutil-getconfig as documented.

diff --git a/src/core/bin/ocutil-spooler b/src/core/bin/ocutil-spooler
--- a/src/core/bin/ocutil-spooler
+++ b/src/core/bin/ocutil-spooler
@@ -57,6 +57,11 @@ if [ $? -ne 0 ] ; then
 	exit 1
 fi
 
+ocutil-update-dumb-http >> $OC_LOGFILE 2>&1
+if [ $? -ne 0 ] ; then
+	echo "PANIC: ocutil-update-dumb-http failed; consult $OC_LOGFILE"
+	exit 1
+fi
 ocutil-generate-index >> $OC_LOGFILE 2>&1
 if [ $? -ne 0 ] ; then
 	echo "PANIC: ocutil-generate-index failed; consult $OC_LOGFILE"
diff --git a/src/core/bin/ocutil-validate-dirs b/src/core/bin/ocutil-validate-dirs
--- a/src/core/bin/ocutil-validate-dirs
+++ b/src/core/bin/ocutil-validate-dirs
@@ -23,15 +23,26 @@ if [ ! -e "$OC_WWW_ROOT" ] ; then
 	chown "$OC_WWW_USER:$OC_WWW_GROUP" "$OC_WWW_ROOT"
 fi
 
+if [ "$OC_GIT_DUMB_HTTP" == "YES" ] ; then
+	if [ ! -e "$OC_GIT_DUMB_HTTP_DIR" ] ; then
+		mkdir -p "$OC_GIT_DUMB_HTTP_DIR"
+		chown "$OC_WWW_USER:$OC_WWW_GROUP" "$OC_GIT_DUMB_HTTP_DIR"
+	fi
+
+	if [ ! -e "$OC_GIT_DUMB_HTTP_DIR" ] ; then
+		echo "ERROR: '$OC_GIT_DUMB_HTTP_DIR' does not exist and could not create it!"
+		exit 1
+	fi
+fi
 
 if [ ! -d "$OC_GIT_DIR" ] ; then
 	echo "ERROR: '$OC_GIT_DIR' does not exist, and could not create it!"
-	exit 1;
+	exit 1
 fi
 
 if [ ! -d "$OC_GITSPOOL" ] ; then
 	echo "ERROR: '$OC_GITSPOOL' does not exist, and could not create it!"
-	exit 1;
+	exit 1
 fi
 
 if [ ! -e "$OC_WWW_ROOT" ] ; then
