Build system improvements.
* Makefile is now just for building redist files, will no longer install
* Separate installer script will be added shortly
* Added dirname and basename to ocutil-validate-dep
* Added utilities to inject a shared header into all scripts which will
  load configs from /etc/, which is the first step to getting rid of
  ocutil-getconfig.

diff --git a/src/core/bin/ocutil-validate-dep b/src/core/bin/ocutil-validate-dep
--- a/src/core/bin/ocutil-validate-dep
+++ b/src/core/bin/ocutil-validate-dep
@@ -16,3 +16,13 @@ if [ ! -e `which git` ] ; then
 	echo "ERROR: dependency 'git' is not in PATH!"
 	exit 1
 fi
+
+if [ ! -e `which dirname` ] ; then
+	echo "ERROR: dependency 'dirname' is not in PATH!"
+	exit 1
+fi
+
+if [ ! -e `which basename` ] ; then
+	echo "ERROR: dependency 'basename' is not in PATH!"
+	exit 1
+fi
