Implemented installer, and switched to a new configuration model.
* Installation is now accomplished via ./install.pl - the makefile only
  builds the redistributeable tarball.
* Configuration is now stored in /etc/openchariot.
* Configuration sourcing is now burned into src/core/bin/* while
  building the redist tarball.
* Version is now tracked in the VERSION file and is inserted into the
  configuration headers during building
* Configuration is no longer overwritten during installation
* Implemented uninstaller script (./uninstall.pl)

diff --git a/src/core/bin/ocutil-validate-dep b/src/core/bin/ocutil-validate-dep
--- a/src/core/bin/ocutil-validate-dep
+++ b/src/core/bin/ocutil-validate-dep
@@ -2,27 +2,37 @@
 
 # Validate that required dependencies are in $PATH
 
-if [ ! -e `which be` ] ; then
+if [ ! -e "`which be`" ] ; then
 	echo "ERROR: dependency 'be' is not in PATH!"
 	exit 1
 fi
 
-if [ ! -e `which gitstats` ] ; then
+if [ ! -e "`which gitstats`" ] ; then
 	echo "ERROR: dependency 'gitstats' is not in PATH!"
 	exit 1
 fi
 
-if [ ! -e `which git` ] ; then
+if [ ! -e "`which git-arr`" ] ; then
+	echo "ERROR: dependency 'git-arr' is not in PATH!"
+	exit 1
+fi
+
+if [ ! -e "`which git`" ] ; then
 	echo "ERROR: dependency 'git' is not in PATH!"
 	exit 1
 fi
 
-if [ ! -e `which dirname` ] ; then
+if [ ! -e "`which dirname`" ] ; then
 	echo "ERROR: dependency 'dirname' is not in PATH!"
 	exit 1
 fi
 
-if [ ! -e `which basename` ] ; then
+if [ ! -e "`which basename`" ] ; then
 	echo "ERROR: dependency 'basename' is not in PATH!"
+	exit 1
+fi
+
+if [ ! -e "`which rsync`" ] ; then
+	echo "ERROR: dependency 'rsync' is not in PATH!"
 	exit 1
 fi
