Implemented basic index generation.
A plain HTML page with an index of projects is now generated. The page
includes the projects description from .git, as well as links to the
README, bug tracker, project statistics, and documentation; all of which
will fail gracefully should they not exist on the server yet.

diff --git a/src/core/bin/ocutil-spooler b/src/core/bin/ocutil-spooler
--- a/src/core/bin/ocutil-spooler
+++ b/src/core/bin/ocutil-spooler
@@ -56,4 +56,10 @@ if [ $? -ne 0 ] ; then
 	echo "PANIC: ocutil-update-www-perm failed; consult $OC_LOGFILE"
 	exit 1
 fi
+
+ocutil-generate-index >> $OC_LOGFILE 2>&1
+if [ $? -ne 0 ] ; then
+	echo "PANIC: ocutil-generate-index failed; consult $OC_LOGFILE"
+	exit 1
+fi
 echo "$0 stopped at $(date)" >> $OC_LOGFILE
